const SET_CREDENTIALS = 'SET_CREDENTIALS';
const RECEIVE_USER_INFO = 'RECEIVE_USER_INFO';
const SET_PROFILE_PHOTO = 'SET_PROFILE_PHOTO';
const LOG_OUT = 'LOG_OUT';

export {
  SET_CREDENTIALS,
  RECEIVE_USER_INFO,
  SET_PROFILE_PHOTO,
  LOG_OUT
};
