const SET_CREDENTIALS = 'SET_CREDENTIALS';
const RECEIVE_USER_INFO = 'RECEIVE_USER_INFO';
const SET_PROFILE_PHOTO = 'SET_PROFILE_PHOTO';
const RECEIVE_DATES = 'RECEIVE_DATES';
const SET_REFRESHED = 'SET_REFRESHED';
const SET_LAST_SUMMER = 'SET_LAST_SUMMER';
const LOG_OUT = 'LOG_OUT';

export {
  SET_CREDENTIALS,
  RECEIVE_USER_INFO,
  SET_PROFILE_PHOTO,
  RECEIVE_DATES,
  SET_REFRESHED,
  SET_LAST_SUMMER,
  LOG_OUT
};
